apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcp-glbc-hacbs
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: app
    repoURL: https://github.com/gbenhaim/kcp-glbc-hacbs
    targetRevision: main
  destination:
    namespace: kcp-glbc-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
